Repository devosu/event-feed-project, pull requests merged in 2024-04, with the labels that each got.

#1 Ready to merge and deploy production with latest main.
  .babelrc
  .eslintrc.json
  .github/workflows/production-deploy.yml
  .gitignore
  .prettierrc.json
  README.md
  firebase/.env.example
  firebase/firebase.js
  firebase/firebase.test.js
  package-lock.json
  package.json
  src/components/exampleComp.js
  src/components/exampleComp.test.js
  src/components/healthCheckComp.js
  src/components/healthCheckComp.test.js
  src/index.js
  src/media/Logo.png
  src/pages/App.js
  src/pages/App.test.js
  src/pages/Home.js
  src/pages/Home.test.js
  src/pages/Yakob.js
  src/pages/Yakob.test.js
  src/pages/Ziqi.js
  src/pages/Ziqi.test.js
  src/reportWebVitals.js
  src/setupTests.js
  src/static/yakob.css
  src/static/ziqi.css
Labels: enhancement

#21 Added Firebase functionality
  .firebaserc
  firebase.json
  firestore.indexes.json
  firestore.rules
  jsconfig.json
  next.config.cjs
  next.config.js
  package-lock.json
  src/app/page.js
  src/firebase/firebase.js
  src/firebase/firestore.js
Labels: feature, deployment

#27 Fixed workflow, now just need to fix the broken testes.
  .github/workflows/cicd-issue-create.yml
  src/app/components/eventCard.js
  src/app/components/eventCard.test.js
  src/app/create/page.js
  src/app/create/page.test.js
  src/app/page.js
  src/app/ziqi/page.client.js
  src/app/ziqi/page.js
Labels: bug, deployment

#28 Fixed auto-issue bug needs str not array.
  .github/ISSUE_TEMPLATE/cicd-issue-template.md
Labels: bug, deployment

#29 Another fix to the auto-issue feature.
  .github/ISSUE_TEMPLATE/cicd-issue-template.md
Labels: bug

#30 Update main's workflow to test auto-issue feature.
  .eslintrc.json
  .github/ISSUE_TEMPLATE/cicd-issue-template.md
  .github/ISSUE_TEMPLATE/cicd-issue-template.yml
  .github/workflows/cicd-issue-create.yml
  .prettierrc.json
  jest.setup.js
  package-lock.json
  package.json
  src/app/components/sampleComponent.js
  src/app/components/sampleComponent.test.js
  src/app/create/page.js
  src/app/create/page.test.js
  src/app/page.js
  src/firebase/firebase.js
  src/firebase/fireseed.js
  src/firebase/fireseed.test.js
  src/firebase/firestore.js
  src/firebase/firestore.test.js
Labels: CICD

#31 New fix to auto-issue template title, getting close to working.
  .github/ISSUE_TEMPLATE/cicd-issue-template.yml
Labels: bug, CICD

#32 Simplified template, trying again.
  .github/ISSUE_TEMPLATE/cicd-issue-template.yml
  .github/issue-templates/cicd-issue-template.md
  .github/workflows/cicd-issue-create.yml
Labels: bug, CICD

#36 More auto-issue generate testing.
  .github/issue-templates/cicd-issue-template.md
Labels: bug, CICD
